"""
Django settings for spectrum project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Locally this falls back to a dev-only key. In production, set the
# DJANGO_SECRET_KEY environment variable on your host instead.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-r+gxl$7wmvrj1*j&=x0w!z3l81_#*ky+71f4g5^ptkpt6_8o%v",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False on your host once it's deployed.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Set DJANGO_ALLOWED_HOSTS="yourapp.onrender.com,localhost" on your host.
_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS")
ALLOWED_HOSTS = _hosts.split(",") if _hosts else ["*"]

CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS if h not in ("*", "localhost", "127.0.0.1")
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "agent_portal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise is a production concern: it serves static files straight
    # out of a process-start snapshot of STATIC_ROOT (the collected
    # `staticfiles/` folder), which is exactly the kind of stale-content
    # trap this project got bitten by in local dev (see STATICFILES_STORAGE
    # above) — a leftover staticfiles/ folder from an old collectstatic run
    # would otherwise get served by WhiteNoise forever, no matter what
    # changes in `static/` or in settings.py. Excluding it entirely when
    # DEBUG=True means local dev always goes through Django's own
    # staticfiles app instead, which reads the current file off disk on
    # every single request — nothing to go stale, ever.
    *([] if DEBUG else ["whitenoise.middleware.WhiteNoiseMiddleware"]),
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "spectrum.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "agent_portal.context_processors.topbar_avatar",
            ],
        },
    },
]

WSGI_APPLICATION = "spectrum.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# The manifest storage below bakes a content hash into every static
# filename (style.a1b2c3.css) so production browsers can cache it forever
# and still see new content the instant it changes. That hash is only
# ever written by `collectstatic` — never by `runserver` — so in local
# dev it becomes a trap: edit style.css, restart the server, and
# {% static %} keeps resolving to the *old* hashed filename because
# nothing regenerated the manifest. That's almost certainly why earlier
# CSS/JS edits didn't show up even after replacing files and restarting
# the dev server. Only use the hashed/manifest storage in production
# (DEBUG=False), where the host's build step runs collectstatic on every
# deploy; in local dev, serve the plain unhashed files straight off disk
# so every edit shows up on the very next request, no extra step needed.
#
# NOTE: this must be set via STORAGES (the dict below), not the older
# STATICFILES_STORAGE setting — as of the Django version this project
# pins, STATICFILES_STORAGE is silently ignored entirely (verified by
# inspecting the installed Django source; there's no deprecation shim
# translating it into STORAGES). Setting only STATICFILES_STORAGE here
# looked correct in a settings.py read-through but did *nothing* at
# runtime: `collectstatic` kept copying plain, unhashed files with no
# manifest even with DEBUG=False, which would have silently defeated the
# Round 15 fix in the one place (a real deploy) where the hashed/
# cache-forever storage is actually supposed to run. Caught by actually
# running `collectstatic` under DEBUG=False and checking the output
# directory for a manifest file and hashed filenames, not by reasoning
# about the setting alone.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"
