# Generated by Django 5.2.17 on 2026-08-27 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Incentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="1 = first tier, 2 = next, etc."
                    ),
                ),
                ("emoji", models.CharField(default="⭐", max_length=8)),
                (
                    "color",
                    models.CharField(
                        default="accent",
                        help_text="CSS token used to color this tier's badge (see style.css).",
                        max_length=20,
                    ),
                ),
                ("perk_description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "base_points",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Points earned per unit sold, unless overridden per incentive.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="agent_portal.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncentiveProductGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_quantity",
                    models.PositiveIntegerField(
                        help_text="Suggested units to sell during this incentive period."
                    ),
                ),
                (
                    "points_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overrides the product's base points for this incentive only.",
                        null=True,
                    ),
                ),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_goals",
                        to="agent_portal.incentive",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent_portal.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("incentive", "product")},
            },
        ),
        migrations.AddField(
            model_name="incentive",
            name="products",
            field=models.ManyToManyField(
                through="agent_portal.IncentiveProductGoal", to="agent_portal.product"
            ),
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar_emoji", models.CharField(default="🚀", max_length=8)),
                ("employee_code", models.CharField(max_length=20, unique=True)),
                (
                    "joined_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="agent_portal.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("points_earned", models.PositiveIntegerField()),
                ("sold_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="agent_portal.agentprofile",
                    ),
                ),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="agent_portal.incentive",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="agent_portal.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="IncentiveTierRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_required", models.PositiveIntegerField()),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_rules",
                        to="agent_portal.incentive",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent_portal.tier",
                    ),
                ),
            ],
            options={
                "ordering": ["tier__order"],
                "unique_together": {("incentive", "tier")},
            },
        ),
        migrations.AddField(
            model_name="incentive",
            name="tiers",
            field=models.ManyToManyField(
                through="agent_portal.IncentiveTierRule", to="agent_portal.tier"
            ),
        ),
    ]
