# Generated by Django 5.2.17 on 2026-08-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="current_login_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="last_login_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="longest_login_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AgentAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="agent_portal.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "unique_together": {("agent", "key")},
            },
        ),
    ]
