# Generated by Django 5.2.17 on 2026-08-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0002_agentprofile_current_login_streak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to="agent_portal.agentprofile",
                    ),
                ),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to="agent_portal.incentive",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("agent", "incentive", "key")},
            },
        ),
    ]
