# Generated by Django 5.2.17 on 2026-08-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0003_agenttaskcompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentGoalBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_awarded", models.PositiveIntegerField()),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_bonuses",
                        to="agent_portal.agentprofile",
                    ),
                ),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_bonuses",
                        to="agent_portal.incentive",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent_portal.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "unique_together": {("agent", "incentive", "product")},
            },
        ),
    ]
