# Generated by Django 5.2.17 on 2026-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0004_agentgoalbonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
    ]
