# Generated by Django 5.2.17 on 2026-09-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0005_sale_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="last_seen_level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="last_spin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="streak_freezes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AgentLoginDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "used_streak_freeze",
                    models.BooleanField(
                        default=False,
                        help_text="True if this day's entry only exists because a streak freeze covered a gap.",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_days",
                        to="agent_portal.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("agent", "date")},
            },
        ),
        migrations.CreateModel(
            name="AgentSpinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("prize_key", models.CharField(max_length=50)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("spun_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spin_results",
                        to="agent_portal.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-spun_at"],
                "unique_together": {("agent", "date")},
            },
        ),
        migrations.CreateModel(
            name="AgentWeeklyChallengeCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_year", models.PositiveIntegerField()),
                ("iso_week", models.PositiveSmallIntegerField()),
                ("key", models.CharField(max_length=50)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_challenge_completions",
                        to="agent_portal.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("agent", "iso_year", "iso_week", "key")},
            },
        ),
    ]
