# Generated by Django 5.2.17 on 2026-09-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0006_agentprofile_last_seen_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentprofile",
            name="last_spin_date",
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="highest_clean_streak_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="last_clean_streak_seen",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="longest_clean_streak_ever",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sale",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgentCleanStreakAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streak_length", models.PositiveIntegerField()),
                ("points_awarded", models.PositiveIntegerField()),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clean_streak_awards",
                        to="agent_portal.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.DeleteModel(
            name="AgentSpinResult",
        ),
    ]
