# Generated by Django 5.2.17 on 2026-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_portal", "0007_remove_agentprofile_last_spin_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="last_seen_positive_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
